# Use PHP 8.3 FPM as the base image
FROM php:8.4-fpm
ARG USER=www-data
ARG USER

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
# Install system dependencies for PHP extensions
RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions amqp bcmath gd intl opcache pdo_mysql pdo_pgsql sockets xsl zip xdebug pcov

RUN docker-php-ext-enable xdebug \
    && echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.client_host = host.docker.internal" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

# Install Composer globally
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set the working directory inside the container
WORKDIR /app
RUN chown -R ${USER}:${USER} /app

COPY composer.* ./




#### This is project specific ####

# Composer install
#RUN composer install --prefer-dist --no-scripts --no-interaction
# Copy the entrypoint script
#COPY ./.server/docker/entrypoint.sh /usr/local/bin/entrypoint.sh
# Ensure the entrypoint script is executable
#RUN chmod +x /usr/local/bin/entrypoint.sh
# Use the entrypoint script
#ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
